server:
  port: 8888
spring:
  application:
    name: tsp-config-server
  security:
    user:
      name: user
      password: 123456
  cloud:
#    inetutils:
#      preferredNetworks: 192.168
    config:
      server:
        git:
#          uri: appuser@10.130.151.106:/data/gitrepo/tsp-config.git
          uri: /tsp/git/tsp-git-repo/mqtt-fin
          ignoreLocalSshSettings: true
#          search-paths: dev2          privateKey: |
                       -----BEGIN RSA PRIVATE KEY-----
                       MIIEogIBAAKCAQEA4JCMuId8FN2DnXGoLe6o7ktudE6YA3aEPDKtqhQ1iMQcpMp/
                       XcMna7bmWWeZB9u3Pjvto6dKXuPSCpyWIEKU4xgHVlJKbPKsFpayMW+1q+CGc7Al
                       +CcaKJS0ogKyaKrWz/xrZFoKWwtvDfHUtUBfXvVVgK2E/loyMeRI4/Lh8kCnENDT
                       PnpDlkStHZqvRg82IKbGbTlTzMomhzL0Y/7qxCTtoCie6rKIqzSr1lT60RCG1RQE
                       S53UtGDSiXDP8QDJtgPmwCbTDGAhupRqRdGpkPEVfZzir+WqViYT+fPYd+UqNKGm
                       Q7PMbWwcA72ys8f7msd6foQotLIHP3vJbswYKwIDAQABAoIBAHyemwkYXrpxh0WL
                       OkprJCJBiAVRTDi3v4Bsm0VEO8UvF7o3ieDtmOXEtSYuQJVEz/bgaOslvjbUdM5g
                       wUsbx+YSgpfbyOOW8/sBG9glZwr/6X0v5pJEmNamV2uE1Z8SF22KZcpl0VNfD/0M
                       E/+VvpdCzHVBVgmU4kAfsHeXZN37CqE8cDSxqn5SD9duC4vXaNBHBZYOyXKdkqu1
                       NIRUmWTcw4Jt6xUxUyArqU0aaCX8OcjQ9zXzwj8KQqAm012nHQZ5qF9q5yNIFupa
                       8fnYhPWdWwQZvP3y+5j3kWEJNzn57Gra7A6KUoqqCUfaaJxLE50oSv7zot6+ERle
                       jE5DGGkCgYEA+hFh6eiJdDhZd/pn4TZNexhpk6mwOravg2Ql2tpPywOKUg+++3+G
                       Lgjo97/046TUl5dwYfZw6OXBcns/dCUl66fKAr+9pHiwjr75Xdd1448gj8RTGqzI
                       DIutgJ0BulqHVILIu+E4SiGAGS5ruwX7mw5xPKg0W8Lq22MPgKmZo30CgYEA5eRK
                       YEsQ/ae5tVzgYsnfz31XI0jZ0Tc444GZcOUFVQbqPm4k22fgS7qftcyt8lsz1ZVe
                       FsdiAfBkVbK/GTfrtsKLopoiAANLRH7KsWXNe3MP6vgQOueAhFhssQHF4DvdhMwo
                       FVjmVrYfKBPD1y6e3vPEnlGIBaIyKiePMViRqscCgYA9xpmHrVh3i4wepY+QBVgy
                       tp8uSVctyf+l19G6NQBNSLyc9SLbAm/lY3IZ8iPPMOML5+9tY/IUtt2JKIVObfbm
                       NncjIrb4sI/9U5RK6HVJGAyVN4zIJDLvVnowMZlBrieMaxqnv0WmmowIrH0UoK+9
                       aF30/CCjIo3eUKR9xmgcCQKBgBJotYwAdtvZEoXzagR/Jez3nIK20rpuMaAGQMNJ
                       k6O7agaVy13Gc6+cwi1MtqExrHTuARrR3IdLOL2kEqlyUO3Rplze+toFaYGSpaiO
                       /mVkUWH/e008PI5chlemTLIoGRUJRCxxcgB/lP8glg4lLZOs8ZG79ah91IaLpGvP
                       K9sBAoGAdjkxivA04vzWxDl36+qZISAl0LWIK9Z7gd8u6MzWfQLQ4bA4WLi4ZdxL
                       owsRxjFjZkLU00J0k3li+RhT34DTtVxCkHWdNmAIb2BFbR05/XUWn0OCcPrZLcA7
                       pcpdNOqoQYAP6mBQDp8rkEwJPuv7Inc8CMQGgpzZJLk4e9Iw3sk=
                       -----END RSA PRIVATE KEY-----
eureka:   
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
#      defaultZone: http://10.130.151.197:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
  
management:
  endpoints:
    web:
      exposure:
        include: info, health, refresh, loggers